# Generated by Django 5.2.3 on 2025-06-24 15:20

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish/'),
        ),
    ]
