# Generated by Django 5.2.3 on 2025-06-24 15:24

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/dish/'),
        ),
    ]
